branch-defaults:
  main:
    environment: NUGU-play-FAFA
    group_suffix: null
environment-defaults:
  NUGU-play-FAFA:
    branch: null
    repository: null
global:
  application_name: NUGU-play-FAFA
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
